export const MESS_LIST_REQUEST = 'MESS_LIST_REQUEST';
export const MESS_LIST_SUCCESS = 'MESS_LIST_SUCCESS';
export const MESS_LIST_FAIL = 'MESS_LIST_FAIL';

export const MESS_DETAILS_REQUEST = 'MESS_DETAILS_REQUEST';
export const MESS_DETAILS_SUCCESS = 'MESS_DETAILS_SUCCESS';
export const MESS_DETAILS_FAIL = 'MESS_DETAILS_FAIL';