export const MESS_LIST_REQUEST = 'MESS_LIST_REQUEST';
export const MESS_LIST_SUCCESS = 'MESS_LIST_SUCCESS';
export const MESS_LIST_FAIL = 'MESS_LIST_FAIL';

export const MESS_DETAILS_REQUEST = 'MESS_DETAILS_REQUEST';
export const MESS_DETAILS_SUCCESS = 'MESS_DETAILS_SUCCESS';
export const MESS_DETAILS_FAIL = 'MESS_DETAILS_FAIL';

export const MESS_DELETE_REQUEST = 'MESS_DELETE_REQUEST';
export const MESS_DELETE_SUCCESS = 'MESS_DELETE_SUCCESS';
export const MESS_DELETE_FAIL = 'MESS_DELETE_FAIL';

export const MESS_UPDATE_REQUEST = 'MESS_UPDATE_REQUEST';
export const MESS_UPDATE_SUCCESS = 'MESS_UPDATE_SUCCESS';
export const MESS_UPDATE_FAIL = 'MESS_UPDATE_FAIL';
export const MESS_UPDATE_RESET = 'MESS_UPDATE_RESET';

export const MESS_ADD_REQUEST = 'MESS_ADD_REQUEST';
export const MESS_ADD_SUCCESS = 'MESS_ADD_SUCCESS';
export const MESS_ADD_FAIL = 'MESS_ADD_FAIL';
export const MESS_ADD_RESET = 'MESS_ADD_RESET';

export const MESS_SEARCH_REQUEST = 'MESS_SEARCH_REQUEST';
export const MESS_SEARCH_SUCCESS = 'MESS_SEARCH_SUCCESS';
export const MESS_SEARCH_FAIL = 'MESS_SEARCH_FAIL';