export const ROOM_LIST_REQUEST = 'ROOM_LIST_REQUEST';
export const ROOM_LIST_SUCCESS = 'ROOM_LIST_SUCCESS';
export const ROOM_LIST_FAIL = 'ROOM_LIST_FAIL';

export const ROOM_DETAILS_REQUEST = 'ROOM_DETAILS_REQUEST';
export const ROOM_DETAILS_SUCCESS = 'ROOM_DETAILS_SUCCESS';
export const ROOM_DETAILS_FAIL = 'ROOM_DETAILS_FAIL';

export const ROOMSET_DELETE_REQUEST = 'ROOMSET_DELETE_REQUEST';
export const ROOMSET_DELETE_SUCCESS = 'ROOMSET_DELETE_SUCCESS';
export const ROOMSET_DELETE_FAIL = 'ROOMSET_DELETE_FAIL';

export const ROOMSET_ADD_REQUEST = 'ROOMSET_ADD_REQUEST';
export const ROOMSET_ADD_SUCCESS = 'ROOMSET_ADD_SUCCESS';
export const ROOMSET_ADD_FAIL = 'ROOMSET_ADD_FAIL';
export const ROOMSET_ADD_RESET = 'ROOMSET_ADD_RESET';

export const ROOM_SEARCH_REQUEST = 'ROOM_SEARCH_REQUEST';
export const ROOM_SEARCH_SUCCESS = 'ROOM_SEARCH_SUCCESS';
export const ROOM_SEARCH_FAIL = 'ROOM_SEARCH_FAIL';